# name: 'auth'

# on:
#   push:
#     paths:
#       - 'packages/auth/**'
#       - '.github/workflows/auth.yaml'

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1

#       - name: Run tests
#         run: |-
#           cd routes/auth
#           go test ./...
