/** This file generated by @midwayjs/bundle-helper */
export * from './config/config.default';
export * from './demo.controller';
export { AutoConfiguration as Configuration } from './configuration';
