/** This file generated by @midwayjs/bundle-helper */
export { AutoConfiguration as Configuration } from './configuration';
export * from './config/condig.development';
export * from './config/config.default';
export * from './demo.service';
export * from './demo.controller';
export * from './utils/index';
