# This is the development environment docker-compose.yml

version: '3.9'

x-logging: &loki-logging
  driver: loki:latest
  options:
    loki-url: 'http://loki:3100/loki/api/v1/push'
    max-size: '300m'

services:
  mysql:
    image: mysql:8.0.32
    env_file:
      - ${CONFIG_DIR:-.}/.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    logging: *loki-logging

  portainer-agent:
    image: portainer/agent:2.11.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.11.0
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    ports:
      - 13331:9443
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data:rw
      - ${CONFIG_DIR:-.}/config/redis:/usr/local/etc/redis:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    logging: *loki-logging

networks:
  default:
    driver: overlay
    attachable: true
  agent_network:
    driver: overlay
    attachable: true

volumes:
  etcd_data:
    driver: local
  mysql_data:
  postgres_data:
  grafana_data:
  portainer_data:
  prometheus_data:
  loki_data:
  redis_data:
  apisix_logs:
  nacos_logs:
  loki_logs:
  # lets storage
  lets_uploads: