# This is the development environment docker-compose.yml
version: '3.9'

services:
  # traefik:
  #   image: traefik:v2.10.3
  #   command:
  #     - --log.level=DEBUG
  #     - --api.insecure=true
  #     - --api.dashboard=true
  #     - --entrypoints.web.address=:80
  #     # - --entrypoints.websecure.address=:443
  #     # - --entrypoints.websecure.http.tls.certResolver=leresolver
  #     # - --entrypoints.web.http.redirections.entryPoint.to=websecure
  #     # - --entrypoints.web.http.redirections.entryPoint.scheme=https
  #     - --providers.file.watch=true
  #     - --providers.file.filename=/etc/traefik/dynamic/conf.d/dynamic.yaml
  #     - --providers.docker=true
  #     # - --providers.docker.swarmMode=true
  #     - --providers.docker.exposedbydefault=false
  #     - --providers.docker.endpoint=unix:///var/run/docker.sock
  #     # - --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
  #     # - --certificatesresolvers.leresolver.acme.httpchallenge=true
  #     # - --certificatesresolvers.leresolver.acme.email=dev@indiebase.com
  #     # - --certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json
  #     # - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./config/traefik/dynamic.yaml:/etc/traefik/dynamic/conf.d/dynamic.yaml:ro
  #     # - ./config/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
  #     - ./config/traefik/letsencrypt:/letsencrypt:rw,mode=0600
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.middlewares.auth.basicauth.removeheader=true
  #     # "username:password(Get MD5 from htpasswd or online tools NB:double all $ to $$ to avoid docker-compose) 
  #     # indiebase:indiebase
  #     - traefik.http.middlewares.auth.basicauth.users=indiebase:$$apr1$$2p04.Erm$$7exR7Rt5CvrTEswQ5Flfb0
  #     - traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)
  #     # - traefik.http.routers.router1.tls.domains[0].main=traefik.localhost
  #     # - traefik.http.routers.router1.tls.domains[0].sans=*.localhost
  #     - traefik.http.routers.dashboard.entrypoints=web
  #     - traefik.http.routers.dashboard.service=api@internal
  #     # - traefik.http.routers.dashboard.tls=true
  #     # - traefik.http.routers.dashboard.tls.certresolver=leresolver
  #     - traefik.http.routers.dashboard.middlewares=auth
  #     # - traefik.http.services.dashboard.loadbalancer.server.scheme=https
  #   networks:
  #     - traefik

  mon:
    image: quay.io/ceph/daemon:v7.0.3-stable-7.0-quincy-centos-stream8-x86_64
    command: mon
    restart: "no"
    # restart: "unless-stopped"
    environment:
      TZ: UTC
      LANG: en_US.utf8
      CEPH_PUBLIC_NETWORK: 192.168.42.0/24
      MON_IP: 192.168.42.100
      # NEW_USER_KEYRING: 1
    networks:
      ceph_network:
        ipv4_address: 192.168.42.100
    volumes:
      - /dev:/dev
      - ceph_etc:/etc/ceph
      - ceph_lib:/var/lib/ceph

  mgr:
    image: quay.io/ceph/daemon:v7.0.3-stable-7.0-quincy-centos-stream8-x86_64
    command: mgr
    restart: "no"
    # restart: "unless-stopped"
    environment:
      TZ: UTC
      LANG: en_US.utf8
      CEPH_DAEMON: mgr
    depends_on:
      - mon
    networks:
      ceph_network:
        ipv4_address: 192.168.42.101
    volumes:
      - ceph_etc:/etc/ceph
      - ceph_lib:/var/lib/ceph
    ports:
      - 18443:8443
      - 18080:8080

  osd:
    image: quay.io/ceph/daemon:v7.0.3-stable-7.0-quincy-centos-stream8-x86_64
    command: osd
    restart: "no"
    environment:
      TZ: UTC
      LANG: en_US.utf8
      OSD_DEVICE: /dev/loop3
    networks:
      ceph_network:
        ipv4_address: 192.168.42.102
    depends_on:
      - mgr
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime
      - ceph_etc:/etc/ceph
      - ceph_lib:/var/lib/ceph
      # - ceph_osd:/var/lib/ceph/osd

  rgw:
    image: quay.io/ceph/daemon:v7.0.3-stable-7.0-quincy-centos-stream8-x86_64
    command: rgw
    restart: "no"
    environment:
      TZ: UTC
      LANG: en_US.utf8
    volumes:
      - ceph_etc:/etc/ceph
      - ceph_lib:/var/lib/ceph
    depends_on:
      - osd
    networks:
      ceph_network:
        ipv4_address: 192.168.42.103
    ports:
      - 7480:7480

  # mds:
  #   image: quay.io/ceph/daemon:v7.0.3-stable-7.0-quincy-centos-stream8-x86_64
  #   command: mds
  #   restart: "no"
  #   # restart: "unless-stopped"
  #   environment:
  #     TZ: UTC
  #     LANG: en_US.utf8
  #     CEPHFS_CREATE: 1
  #   volumes:
  #     - ceph_etc:/etc/ceph
  #     - ceph_lib:/var/lib/ceph
  #   depends_on:
  #     - osd
  #   networks:
  #     ceph_network:
  #       ipv4_address: 192.168.42.104

networks:
  ceph_network:
    ipam:
      config:
        - subnet: 192.168.42.0/24

volumes:
  ceph_lib:
  ceph_osd:
  ceph_etc:
