server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /ext_logs/*log

  # - job_name: docker
  #   docker_sd_configs:
  #     - host: unix:///var/run/docker.sock
  #     - refresh_interval: 5s
