# This is the development environment docker-compose.yml

version: '3.9'


services:
  mon:
    image: quay.io/ceph/daemon:v7.0.3-stable-7.0-quincy-centos-stream8-x86_64
    command: mon
    restart: unless-stopped
    environment:
      TZ: UTC
      LANG: en_US.utf8
      # MON_IP: 192.168.0.18
      CEPH_PUBLIC_NETWORK: 0.0.0.0/0
    # networks:
    #   ceph_network:
    #     ipv4_address: 192.168.0.18
    volumes:
      - ceph_etc:/etc/ceph
      - ceph_lib:/var/lib/ceph
      
  mgr:
    image: quay.io/ceph/daemon:v7.0.3-stable-7.0-quincy-centos-stream8-x86_64
    command: mgr
    restart: unless-stopped
    environment:
      TZ: UTC
      LANG: en_US.utf8
    depends_on:
      - mon
    # networks:
    #   ceph_network:
    #     ipv4_address: 192.168.0.19
    volumes:
      - ceph_etc:/etc/ceph
      - ceph_lib:/var/lib/ceph
    ports:
      - 28443:8443
      - 28080:8080

  osd:
    image: quay.io/ceph/daemon:v7.0.3-stable-7.0-quincy-centos-stream8-x86_64
    command: osd
    restart: unless-stopped
    environment:
      TZ: UTC
      LANG: en_US.utf8
    # networks:
    #   ceph_network:
    #     ipv4_address: 192.168.0.20
    depends_on:
      - mgr
    volumes:
      - ceph_etc:/etc/ceph
      - ceph_lib:/var/lib/ceph
      - ceph_osd:/var/lib/ceph/osd
    privileged: true
    cap_add:
      - SYS_ADMIN

  rgw:
    image: quay.io/ceph/daemon:v7.0.3-stable-7.0-quincy-centos-stream8-x86_64
    command: rgw
    restart: unless-stopped
    environment:
      TZ: UTC
      LANG: en_US.utf8
    volumes:
      - ceph_etc:/etc/ceph
      - ceph_lib:/var/lib/ceph
    depends_on:
      - osd
    # networks:
    #   ceph_network:
    #     ipv4_address: 192.168.0.21
    ports:
      - 17480:7480

  mds:
    image: quay.io/ceph/daemon:v7.0.3-stable-7.0-quincy-centos-stream8-x86_64
    command: mds
    restart: unless-stopped
    environment:
      TZ: UTC
      LANG: en_US.utf8
      CEPHFS_CREATE: 1
    volumes:
      - ceph_etc:/etc/ceph
      - ceph_lib:/var/lib/ceph
    depends_on:
      - osd
    # networks:
    #   ceph_network:
    #     ipv4_address: 192.168.0.22

networks:
  ceph_network:
    ipam: 
      driver: default
      config:
        - subnet:  192.168.0.0/24

volumes:
  ceph_lib:
  ceph_osd:
  ceph_etc:
