import type { Metadata } from 'next';
import { locales } from '~/i18n';
import { fonts } from './fonts';

import '../globals.css';

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: 'Indiebase',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body className={fonts.className}>{children}</body>
    </html>
  );
}
