import {
  INDIEBASE_MGR,
  IsEntityExisted,
  SpecificProjectType,
  T,
} from '@indiebase/server-shared';
import { ApiProperty } from '@nestjs/swagger';
import { IsEmail, IsHash, IsString } from 'class-validator';

export class LocalSignInDTO {
  @ApiProperty({
    description: 'Email as account name',
    default: 'dev@deskbtm.com',
    examples: ['dev@deskbtm.com', 'two@email.com'],
  })
  @IsEntityExisted(
    {
      type: SpecificProjectType.fromHeader,
      table: T.users,
      column: 'email',
    },
    {
      throwExistedMsg: false,
    },
  )
  @IsEmail()
  email!: string;

  @ApiProperty({
    description:
      'Hacker account password, the password needs to be converted to SHA256 for transfer',
    default: '9b1ddbbcf45a850c792465c816bb43423fe9dc6383b6fbc3a16d25be907e3988',
  })
  @IsHash('sha256', {
    message: 'Password needs to be converted to SHA256',
  })
  password!: string;
}

export class AuthDTO {
  @ApiProperty({
    description: 'X-Indiebase-Reference-Id, the ID for business',
    default: INDIEBASE_MGR,
  })
  referenceId!: string;
}

export class CreateOtpDTO {}

export class OtpDTO {
  @ApiProperty({
    description: 'Otp secret',
  })
  secret!: string;

  @ApiProperty({
    description: 'OTP Key Uri',
  })
  uri!: string;

  @ApiProperty({
    description: 'QRcode Uri',
  })
  qrcodeUri!: string;
}

export class VerifyOtpDTO {
  @ApiProperty({
    description: 'Otp secret from /2fa/gen',
  })
  @IsString({
    message: "Secret shouldn't be empty",
  })
  secret!: string;

  @ApiProperty({
    description: 'The code generated by authenticate apps',
  })
  @IsString({
    message: "Token shouldn't be empty",
  })
  token!: string;
}
