version: '3.7'
services:
  umami:
    image: docker.umami.dev/umami-software/umami:mysql-latest
    network_mode: overlay
    ports:
      - w:3000
    restart: always
    environment:
      DATABASE_URL: mysql://root:indiebase@mysql:3306/indiebase-analytics
      DATABASE_TYPE: mysql
      HASH_SALT: ZuC7tNxKDodpApDaQFTJxVeiTBYzbBixE44Wg33GiDI