import type { AppProps } from 'next/app';
import Router from 'next/router';
import NProgress from 'nprogress';
import 'nprogress/nprogress.css';
import { QueryClient, QueryClientProvider } from 'react-query';
import { ReactQueryDevtools } from 'react-query/devtools';
import Head from 'next/head';
import { Layout } from 'components';

const queryClient = new QueryClient();

const isProduction = process.env.NODE_ENV !== 'production';

NProgress.configure({
  showSpinner: false,
});

Router.events.on('routeChangeStart', NProgress.start);
Router.events.on('routeChangeComplete', NProgress.done);
Router.events.on('routeChangeError', NProgress.done);

function LetsCollabApp({
  Component,
  pageProps,
}: AppProps & { Component: any }) {
  return (
    <>
      <Head>
        <title>letscollab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <QueryClientProvider client={queryClient}>
        {isProduction && <ReactQueryDevtools position="bottom-right" />}
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </QueryClientProvider>
    </>
  );
}

export default LetsCollabApp;
