import type { AppProps } from 'next/app';
import Router from 'next/router';
import NProgress from 'nprogress';
import 'nprogress/nprogress.css';
import { QueryClient, QueryClientProvider } from 'react-query';
import { ReactQueryDevtools } from 'react-query/devtools';
import { CssBaseline, ThemeProvider, GlobalStyles } from '@mui/material';
import Head from 'next/head';
import theme from '../components/themes';
import { Footer } from 'components';

const queryClient = new QueryClient();

const isProduction = process.env.NODE_ENV !== 'production';

NProgress.configure({
  showSpinner: false,
});

Router.events.on('routeChangeStart', NProgress.start);
Router.events.on('routeChangeComplete', NProgress.done);
Router.events.on('routeChangeError', NProgress.done);

function LetsCollabApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>letscollab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <GlobalStyles styles={{ a: { textDecoration: 'none' } }} />
      <QueryClientProvider client={queryClient}>
        <ThemeProvider theme={theme()}>
          <CssBaseline />
          {isProduction && <ReactQueryDevtools position="bottom-right" />}
          <Component {...pageProps} />
          <Footer />
        </ThemeProvider>
      </QueryClientProvider>
    </>
  );
}

export default LetsCollabApp;
