import type { AppProps } from 'next/app';
import Router from 'next/router';
import NProgress from 'nprogress';
import 'nprogress/nprogress.css';
import { QueryClient, QueryClientProvider } from 'react-query';
import { ReactQueryDevtools } from 'react-query/devtools';
import Head from 'next/head';
import { Layout } from 'components';
import 'styles/nextra-doc.css';

const queryClient = new QueryClient();

const isProduction = process.env.NODE_ENV === 'production';

NProgress.configure({
  showSpinner: false,
});

if (isProduction) {
  console.debug = () => {};
}

Router.events.on('routeChangeStart', NProgress.start);
Router.events.on('routeChangeComplete', NProgress.done);
Router.events.on('routeChangeError', NProgress.done);

export async function getStaticProps(context) {


  

  return {
    props: {},
  };
}

function LetsCollabApp({
  Component,
  pageProps,
}: AppProps & { Component: any }) {
  const getLayout = Component.getLayout || ((page) => page);
  return (
    <>
      <Head>
        <title>letscollab</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <QueryClientProvider client={queryClient}>
        {!isProduction && <ReactQueryDevtools position="bottom-right" />}
        {/* {getLayout(<Component {...pageProps} />)} */}
        <Layout>{getLayout(<Component {...pageProps} />)}</Layout>
      </QueryClientProvider>
    </>
  );
}

export default LetsCollabApp;
