version: '3.7'

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:2.10.1-alpine
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - '13336:9000'
    networks:
      - apisix

  apisix:
    image: apache/apisix:2.11.0-alpine
    volumes:
      - apisix_logs:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - '13320:9080/tcp'
      - '13321:9091/tcp'
      - '13322:9443/tcp'
      - '13323:9092/tcp'
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - apisix

  etcd:
    image: bitnami/etcd:3.4.15
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: 'true'
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_ADVERTISE_CLIENT_URLS: 'http://0.0.0.0:2379'
      ETCD_LISTEN_CLIENT_URLS: 'http://0.0.0.0:2379'
    ports:
      - '2379:2379/tcp'
    networks:
      - apisix
  prometheus:
    image: prom/prometheus:v2.25.0
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '13334:9090'
    networks:
      - apisix

  grafana:
    image: grafana/grafana:7.3.7
    ports:
      - '13335:3000'
    volumes:
      - './grafana_conf/provisioning:/etc/grafana/provisioning'
      - './grafana_conf/dashboards:/var/lib/grafana/dashboards'
      - './grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini'
    networks:
      - apisix
    

networks:
  apisix:
    driver: overlay
    attachable: true

volumes:
  etcd_data:
    driver: local
  apisix_logs:
