import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Router from 'next/router';
import { useRouter } from 'next/router';
import { TextParticle } from 'city-night';
import { useWindowSize } from 'react-use';
import { isMobile } from 'react-device-detect';

const Home: NextPage = () => {
  const router = useRouter();
  const { width, height } = useWindowSize();
  console.log(width, height);

  return (
    <div>
      <Head>
        <title>letscollab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main>
        <TextParticle
          text="letscollab"
          resolution={5}
          boxWidth={width}
          boxHeight={height}
          size={300}
        />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
