---
log:
  level: WARN  # ERROR, DEBUG, PANIC, FATAL, ERROR, WARN, INFO
providers:
  docker:
    exposedByDefault: false
    constraints: "Label(`traefik.constraint.label`,`indiebase`)"
    endpoint: 'unix:///var/run/docker.sock'
    network: traefik_default
  file:
    directory: /etc/traefik/dynamic/conf.d
    watch: true
api:
  dashboard: true
entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https      
  websecure:
    address: ':443'
certificatesResolvers:
  leresolver:
    acme:
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: dev@indiebase.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
global:
  checkNewVersion: true
  sendAnonymousUsage: true