version: '3.9'

services:
  portainer-agent:
    image: portainer/agent:2.18.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.18.4
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify
    ports:
      - 9443:9443
      - 9000:9000
      - 8000:8000
    volumes:
      - portainer_data:/data
    networks:
      - portainer_agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  portainer_agent:
    driver: overlay
    attachable: true

volumes:
  portainer_data: